# -*- coding: utf-8 -*-
"""milestone_2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKfIYbQTkPTXHScH9YAwuC9InyzYL6-k
"""

import random
word_list = ["apple", "orange", "banana", "peach", "watermelon"]
print(word_list)
word = random.choice(word_list)
print(word)
guess = input(f"Please enter a single letter. Thanks  ")
if len(guess) == 1 and guess.isalpha:
  print("Good guess!")
else:
  print("Oops! That is not a valid input.")